using System;
namespace LeagueOS.DTO.Matches {
    public class ParticipantStatsDto {
        public long physicalDamageDealt { get; set; }
        public int neutralMinionsKilledTeamJungle { get; set; }
        public long magicDamageDealt { get; set; }
        public int totalPlayerScore { get; set; }
        public int deaths { get; set; }
        public bool win { get; set; }
        public int neutralMinionsKilledEnemyJungle { get; set; }
        public int altarsCaptured { get; set; }
        public int largestCriticalStrike { get; set; }
        public long totalDamageDealt { get; set; }
        public long magicDamageDealtToChampions { get; set; }
        public int visionWardsBoughtInGame { get; set; }
        public long damageDealtToObjectives { get; set; }
        public int largestKillingSpree { get; set; }
        public int item1 { get; set; }
        public int quadraKills { get; set; }
        public int teamObjective { get; set; }
        public int totalTimeCrowdControlDealt { get; set; }
        public int longestTimeSpentLiving { get; set; }
        public int wardsKilled { get; set; }
        public bool firstTowerAssist { get; set; }
        public bool firstTowerKill { get; set; }
        public int item2 { get; set; }
        public int item3 { get; set; }
        public int item0 { get; set; }
        public bool firstBloodAssist { get; set; }
        public long visionScore { get; set; }
        public int wardsPlaced { get; set; }
        public int item4 { get; set; }
        public int item5 { get; set; }
        public int item6 { get; set; }
        public int turretKills { get; set; }
        public int tripleKills { get; set; }
        public long damageSelfMitigated { get; set; }
        public int champLevel { get; set; }
        public int nodeNeutralizeAssist { get; set; }
        public bool firstInhibitorKill { get; set; }
        public int goldEarned { get; set; }
        public long magicalDamageTaken { get; set; }
        public int kills { get; set; }
        public int doubleKills { get; set; }
        public int nodeCaptureAssist { get; set; }
        public long trueDamageTaken { get; set; }
        public int nodeNeutralize { get; set; }
        public bool firstInhibitorAssist { get; set; }
        public int assists { get; set; }
        public int unrealKills { get; set; }
        public int neutralMinionsKilled { get; set; }
        public int objectivePlayerScore { get; set; }
        public int combatPlayerScore { get; set; }
        public long damageDealtToTurrets { get; set; }
        public int altarsNeutralized { get; set; }
        public long physicalDamageDealtToChampions { get; set; }
        public int goldSpent { get; set; }
        public long trueDamageDealt { get; set; }
        public long trueDamageDealtToChampions { get; set; }
        public int participantId { get; set; }
        public int pentaKills { get; set; }
        public long totalHeal { get; set; }
        public int totalMinionsKilled { get; set; }
        public bool firstBloodKill { get; set; }
        public int nodeCapture { get; set; }
        public int largestMultiKill { get; set; }
        public int sightWardsBoughtInGame { get; set; }
        public long totalDamageDealtToChampions { get; set; }
        public int totalUnitsHealed { get; set; }
        public int inhibitorKills { get; set; }
        public int totalScoreRank { get; set; }
        public long totalDamageTaken { get; set; }
        public int killingSprees { get; set; }
        public long timeCCingOthers { get; set; }
        public long physicalDamageTaken { get; set; }
    }
}
