
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HPaned hpaned3;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.TextView textview1;

	private global::Gtk.VPaned vpaned3;

	private global::Gtk.Entry entry1;

	private global::Gtk.Image image5;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned3 = new global::Gtk.HPaned();
		this.hpaned3.CanFocus = true;
		this.hpaned3.Name = "hpaned3";
		this.hpaned3.Position = 119;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.scrolledwindow1.Add(this.textview1);
		this.hpaned3.Add(this.scrolledwindow1);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned3[this.scrolledwindow1]));
		w2.Resize = false;
		// Container child hpaned3.Gtk.Paned+PanedChild
		this.vpaned3 = new global::Gtk.VPaned();
		this.vpaned3.CanFocus = true;
		this.vpaned3.Name = "vpaned3";
		this.vpaned3.Position = 42;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vpaned3.Add(this.entry1);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned3[this.entry1]));
		w3.Resize = false;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.image5 = new global::Gtk.Image();
		this.image5.Name = "image5";
		this.vpaned3.Add(this.image5);
		this.hpaned3.Add(this.vpaned3);
		this.Add(this.hpaned3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
